import pandas as pd
import subprocess
import os
import sys
from datetime import datetime

# 目标股票池 (10只代表性股票)
STOCK_POOL = {
    "000001": "平安银行",
    "600519": "贵州茅台",
    "300750": "宁德时代",
    "002594": "比亚迪",
    "601126": "四方股份",
    "002050": "三花智控",
    "601318": "中国平安",
    "000021": "深科技",
    "600030": "中信证券",
    "300059": "东方财富"
}

START_DATE = "2025-01-01"
END_DATE = "2025-12-31"

results = []

print(f"🚀 开始批量回测: {len(STOCK_POOL)} 只股票 | {START_DATE} ~ {END_DATE}")
print("="*80)

for code, name in STOCK_POOL.items():
    print(f"\n🔄 正在分析: {name} ({code})...")
    
    # Run V1 (Technical) using subprocess to simulate command line execution efficiently
    # Using python3 interpreter
    try:
        # V1 Backtest
        cmd_v1 = [sys.executable, "backtest_engine.py", code, "--start", START_DATE, "--end", END_DATE]
        # Calculate Benchmark (Buy & Hold) from V1 data usually, but here we run full logic
        # We capture output to parse final asset
        # To simplify, we will modify the engines to return JSON or save CSV, 
        # but for this runner we will parsing CSVs generated by engines.
        
        subprocess.run(cmd_v1, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        
        # Read V1 Result
        v1_file = f"backtest_v1_{code}.csv"
        df_v1 = pd.read_csv(v1_file)
        
        # 初始资金
        initial_capital = 100000
        
        # V1 Final Return
        v1_final = df_v1.iloc[-1]['总资产']
        v1_roi = (v1_final - initial_capital) / initial_capital * 100
        
        # Benchmark (Buy & Hold) Calculation
        # Assuming the first close is buy price, last close is sell price
        first_close = df_v1.iloc[0]['收盘']
        last_close = df_v1.iloc[-1]['收盘']
        benchmark_roi = (last_close - first_close) / first_close * 100
        
        # V2 Backtest
        cmd_v2 = [sys.executable, "backtest_engine_v2.py", code, "--start", START_DATE, "--end", END_DATE]
        subprocess.run(cmd_v2, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        
        # Read V2 Result
        v2_file = f"backtest_v2_{code}.csv"
        df_v2 = pd.read_csv(v2_file)
        v2_final = df_v2.iloc[-1]['总资产']
        v2_roi = (v2_final - initial_capital) / initial_capital * 100
        
        # Determine Winner
        if v1_roi > v2_roi and v1_roi > benchmark_roi:
            winner = "V1 (激进)"
        elif v2_roi > v1_roi and v2_roi > benchmark_roi:
            winner = "V2 (稳健)"
        elif benchmark_roi > v1_roi and benchmark_roi > v2_roi:
            winner = "基准 (持有)"
        else:
            winner = "平局"
            
        print(f"   📊 结果: V1={v1_roi:.2f}% | V2={v2_roi:.2f}% | 基准={benchmark_roi:.2f}%")
        
        results.append({
            "代码": code,
            "名称": name,
            "基准涨幅": f"{benchmark_roi:.2f}%",
            "V1收益 (MA5)": f"{v1_roi:.2f}%",
            "V2收益 (MA10)": f"{v2_roi:.2f}%",
            "超额收益(V1 vs 基准)": f"{v1_roi - benchmark_roi:.2f}%",
            "超额收益(V2 vs 基准)": f"{v2_roi - benchmark_roi:.2f}%",
            "胜者": winner
        })

    except Exception as e:
        print(f"❌ 分析 {name} 失败: {e}")

# Generate Summary Report
print("\n" + "="*80)
print("🏆 2025年度 策略回测终极战报")
print("="*80)

df_summary = pd.DataFrame(results)
print(df_summary.to_markdown(index=False))

# Save
df_summary.to_csv("backtest_summary_2025.csv", index=False, encoding='utf-8-sig')
print(f"\n✅ 详细报表已保存: backtest_summary_2025.csv")
